// data/moviesData.ts
export const moviesData = [
  {
    id: 1,
    title: "Lucky Baskhar",
    date: "July 27, 2024",
    likes: 103,
    comments: 0,
    category: "Telugu",
    imageUrl:
      "https://cdn.statically.io/img/dulquer.com/wp-content/uploads/2024/07/1526108-lucky-baskar-1024x614.webp",
    directedBy: "Venky Atluri",
    writtenBy: "Venky Atluri",
    producedBy: ["Naga Vamsi S", "Sai Soujanya"],
    starring: ["Dulquer Salmaan", "Meenakshi Chaudhary"],
  },
  {
    id: 2,
    title: "Kalki 2898 AD",
    date: "June 27, 2024",
    likes: 60,
    comments: 0,
    category: "Telugu",
    imageUrl:
      "https://cdn.statically.io/img/dulquer.com/wp-content/uploads/2024/07/1526108-lucky-baskar-1024x614.webp",
    directedBy: "Nag Ashwin",
    writtenBy: "Nag Ashwin",
    producedBy: ["C. Aswani Dutt"],
    starring: ["Prabhas", "Amitabh Bachchan", "Deepika Padukone"],
  },
  {
    id: 3,
    title: "King of Kotha",
    date: "August 24, 2023",
    likes: 20,
    comments: 0,
    category: "Malayalam",
    imageUrl:
      "https://cdn.statically.io/img/dulquer.com/wp-content/uploads/2024/07/1526108-lucky-baskar-1024x614.webp",
    directedBy: "Abhilash Joshiy",
    writtenBy: "Abhilash N. Chandran",
    producedBy: ["Dulquer Salmaan", "Zee Studios"],
    starring: [
      "Dulquer Salmaan",
      "Shabeer Kallarakkal",
      "Prasanna",
      "Gokul Suresh",
      "Aishwarya Lekshmi",
      "Nyla Usha",
      "Chemban Vinod Jose",
    ],
  },
];
export const Fans = [
  {
    id: "01",
    name: "Fan's Name",
    img: "https://i.ibb.co.com/ccMt2Nmq/3b6f066e-859c-4208-bc76-59db773b56bd.jpg",
    bg: "bg-black",
    textColor: "text-white",
    btnBorder: "border-[#d3a262]",
    btnText: "text-white",
  },
  {
    id: "02",
    name: "Fan's Name",
    img: "https://i.ibb.co.com/ccMt2Nmq/3b6f066e-859c-4208-bc76-59db773b56bd.jpg",
    bg: "bg-white",
    textColor: "text-black",
    btnBorder: "border-[#d3a262]",
    btnText: "text-black",
  },
  {
    id: "03",
    name: "Fan's Name",
    img: "https://i.ibb.co.com/ccMt2Nmq/3b6f066e-859c-4208-bc76-59db773b56bd.jpg",
    bg: "bg-white",
    textColor: "text-black",
    btnBorder: "border-[#d3a262]",
    btnText: "text-white",
  },
  {
    id: "04",
    name: "Fan's Name",
    img: "https://i.ibb.co.com/ccMt2Nmq/3b6f066e-859c-4208-bc76-59db773b56bd.jpg",
    bg: "bg-black",
    textColor: "text-white",
    btnBorder: "border-[#d3a262]",
    btnText: "text-black",
  },
  {
    id: "05",
    name: "Fan's Name",
    img: "https://i.ibb.co.com/ccMt2Nmq/3b6f066e-859c-4208-bc76-59db773b56bd.jpg",
    bg: "bg-black",
    textColor: "text-white",
    btnBorder: "border-[#d3a262]",
    btnText: "text-white",
  },
  {
    id: "06",
    name: "Fan's Name",
    img: "https://i.ibb.co.com/ccMt2Nmq/3b6f066e-859c-4208-bc76-59db773b56bd.jpg",
    bg: "bg-white",
    textColor: "text-black",
    btnBorder: "border-[#d3a262]",
    btnText: "text-black",
  },
];
