import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/globals.css";
import NavBar from "@/components/Reuseable/Navbar";
import ClientRouteLoader from "@/components/Reuseable/ClientLoader";
import FooterWrapper from "@/components/Reuseable/FooterWrapper";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Celebrity Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <NavBar />
        <ClientRouteLoader>
          <div>{children}</div>
          <FooterWrapper />
        </ClientRouteLoader>
      </body>
    </html>
  );
}
