import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

// Load Roboto font with variable support
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add other weights if needed
});

export const metadata: Metadata = {
  title: "Celebrity Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>{children}</body>
    </html>
  );
}
